### ISSUE TITLE
Error when trying to use the theme in Hugo v 0.17

### ISSUE THREAD

**Issue by appernetic** [shenoybr/hugo-goa#4] opened 2016-11-05 10:38 UTC
I get this error messages when I try to install your theme in Hugo v 0.17.  When I try to preview, I get error 255.

Started building sites ... ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/li.html:7:29: executing "theme/partials/li.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/li.html ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/li.html:7:29: executing "theme/partials/li.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/li.html ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/content.html:8:40: executing "theme/partials/content.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/content.html ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/content.html:8:40: executing "theme/partials/content.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/content.html ERROR: 

2016/11/05 10:32:06 template.go:132: template: theme/partials/content.html:8:40: executing "theme/partials/content.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/content.html ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/content.html:8:40: executing "theme/partials/content.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/content.html ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/content.html:8:40: executing "theme/partials/content.html" at <.Site.Params.dateFor...>: invalid value; expected string in theme/partials/content.html ERROR: 2016/11/05 10:32:06 template.go:132: template: theme/partials/main_menu.html:2:11: executing "theme/partials/main_menu.html" at : error calling sort: sequence must be provided in theme/partials/main_menu.html Built site for language en: 0 of 4 drafts rendered 0 future content 0 expired content 5 pages created 0 non-page files copied 0 paginator pages created 0 tags created 0 topics created total in 18 ms

**Comment by shenoybr** [comment] 2016-11-07 20:40
@appernetic Thanks for this bug report. Could you let me know if https://github.com/shenoybr/hugo-goa/pull/5 fixed your issue.

**Comment by shenoybr** [comment] 2016-11-07 21:25
@appernetic Could you check your config.toml to see if you are missing `dateFormat`?

**Comment by shenoybr** [comment] 2016-11-07 21:31
I have indeed traced this error to users missing `dateFormat` within their configs. Since this layout uses dates prominently in the theme, this config param is mandatory. If you wish, you could override the default `li.html` and `single.html` within your sites `layouts` directory. For more information: https://gohugo.io/themes/customizing/

**Comment by appernetic** [comment] 2016-12-04 15:36
Hi,
i had time to check it now. I have this in my config: 

dateformat = "Jan 2, 2006"

**Comment by appernetic** [comment] 2016-12-04 15:45
I changed dateformat to dateFormat but still the same error.


Started building sites ... ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/li.html:9:21: executing "theme/partials/li.html" at : error calling len: len of untyped nil in theme/partials/li.html ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/li.html:9:21: executing "theme/partials/li.html" at : error calling len: len of untyped nil in theme/partials/li.html ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/content.html:9:19: executing "theme/partials/content.html" at : error calling len: len of untyped nil in theme/partials/content.html ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/content.html:9:19: executing "theme/partials/content.html" at : error calling len: len of untyped nil in theme/partials/content.html ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/content.html:9:19: executing "theme/partials/content.html" at : error calling len: len of untyped nil in theme/partials/content.html ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/content.html:9:19: executing "theme/partials/content.html" at : error calling len: len of untyped nil in theme/partials/content.html ERROR: 2016/12/04 15:45:15 template.go:132: template: theme/partials/content.html:9:19: executing "theme/partials/content.html" at : error calling len: len of untyped nil in theme/partials/content.html Built site for language en: 0 of 4 drafts rendered 0 future content 0 expired content 6 pages created 0 non-page files copied 0 paginator pages created 0 tags created 0 categories created total in 21 ms

**Comment by shenoybr** [comment] 2016-12-05 16:35
@appernetic I'll take a look

**Comment by arvinsim** [comment] 2016-12-10 13:27
I really like this theme but I am having the same issue as the OP. Hope that the issue will be fixed soon.

**Comment by yeliv** [comment] 2017-01-15 09:39
Still getting this error as well. Is this theme based on Cocoa? Because I have been finding the same bug in all similar themes (this is the third now).

**Comment by nhejazi** [comment] 2017-06-14 03:15
Also really like this theme and having the same problem as OP -- my [config.toml](https://github.com/nhejazi/hugoTest/blob/sources/config.toml) has `dateformat` correct I believe (matches that in the same file under `exampleSite`). Any help would be much appreciated.

**Comment by shenoybr** [comment] 2017-10-10 00:39
I am not able to reproduce this on my end, but this PR probably fixes it https://github.com/shenoybr/hugo-goa/pull/23

**Closed by shenoybr** 2017-10-10 00:39 UTC
